module.exports = {
	ProtocolVersion: require("./ProtocolVersion"),
	RequestAuthLogin: require("./RequestAuthLogin"),
	RequestBypassToServer: require("./RequestBypassToServer"),
	NewCharacter: require("./NewCharacter"),
	Logout: require("./Logout"),
	CharacterCreate: require("./CharacterCreate"),
	CharacterSelected: require("./CharacterSelected"),
	RequestQuestList: require("./RequestQuestList"),
	RequestShowBoard: require("./RequestShowBoard"),
	EnterWorld: require("./EnterWorld"),
	MoveBackwardToLocation: require("./MoveBackwardToLocation"),
	RequestSocialAction: require("./RequestSocialAction"),
	Say2: require("./Say2"),
	StopMove: require("./StopMove"),
	RequestActionUse: require("./RequestActionUse"),
	Action: require("./Action"),
	RequestTargetCancel: require("./RequestTargetCancel"),
	RequestItemList: require("./RequestItemList"),
	RequestUseItem: require("./RequestUseItem"),
	ValidatePosition: require("./ValidatePosition"),
	RequestSkillList: require("./RequestSkillList"),
	RequestMagicSkillUse: require("./RequestMagicSkillUse"),
	RequestAttack: require("./RequestAttack")
}